server:
  port: 8080

spring:
  application:
    name: aws-api
  datasource:
    url: jdbc:mysql://localhost:3306/aws_api
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update